# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoreElation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreElation
  pod 'Firebase/Core'

  target 'CoreElationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CoreElation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoreElation-tvOS

  target 'CoreElation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
